version: 0.2

phases:
  install:
    commands:
      - echo Installing
      - npm install
  pre_build:
    commands:
      - npm -v
      - node -v
  build:
    commands:
      - echo Build started on `date`
      - npm run lint --fix
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "dist"